name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  # fatal warnings
  RUSTFLAGS: -D warnings
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Cargo clippy
      run: cargo clippy

    - name: Cargo test
      run: cargo test

  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
    needs: test
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    timeout-minutes: 30
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --local-only
