name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  # fatal warnings
  RUSTFLAGS: -D warnings
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - run: rustup toolchain install stable --profile minimal

    - uses: Swatinem/rust-cache@v2
    
    - name: Cargo clippy
      run: cargo clippy

    - name: Cargo test
      run: cargo test

  deploy:
    runs-on: ubuntu-22.04
    if: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
    needs: test
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    timeout-minutes: 30
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Docker Buildx and checkout
      id: buildx
      uses: docker/setup-buildx-action@v3 

    - name: 🔑 Fly Registry Auth
      uses: docker/login-action@v3
      with:
        registry: registry.fly.io
        username: ${{ secrets.FLY_USERNAME }}
        password: ${{ secrets.FLY_API_TOKEN }}

    - name: Docker Build And Push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: registry.fly.io/harvest-overtime:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max      

    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: flyctl deploy --image registry.fly.io/harvest-overtime:${{ github.sha }}
